######################################################################
##
## Filename: beatMakerTest.udo
## Created on: Sat Apr 18 5:06:04 PM Central Daylight Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
